name: CI-dianahorban477-bot

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  GITHUB_ACTIONS: "True"

jobs:
  github-task-job:
    # Добавляем имя пользователя в название Job
    name: github-task-job-${{ github.actor }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Display GITHUB_ACTIONS environment variable
        run: |
          echo "GITHUB_ACTIONS: ${{ env.GITHUB_ACTIONS }}"

      - name: Show branch and repo names
        run: |
          echo "Github repository: ${{ github.repository }}"
          echo "Branch name: ${{ github.head_ref }}"
          echo "Base branch: ${{ github.base_ref }}"

      - name: Display triggering event
        run: |
          echo "Event name: ${{ github.event_name }}"
